<?php

namespace AppBundle\Repository;

/**
 * DiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class DiscountRepository extends EntityRepository
{
    function getAll()
    {
        $query = $this->getEntityManager()->createQuery('Select u from AppBundle:Discount u');
        return $query->getArrayResult();
    }
}
